displayName: Presentation Buddy
schemaName: cr7a0_mytooltest_AsoY32
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - id: MsTeams
      channelId: MsTeams

  publishOnCreate: false
  publishOnImport: true
  isLightweightBot: false
  recognizer:
    $kind: CLICopilotRecognizer

  agentSettings:
    $kind: AgentSettings
    instructions:
      $kind: Instructions
      segments:
        - $kind: StaticSegment
          value: |-
            help me research, find previous presentations and create a new presentation on a given topic. ​
            y‌our response should include a request  classification type. ​‌

    model:
      $kind: ModelConfig
      series: Sonnet46

    web:
      $kind: WebSettings
      enableWebSearch: false

publishedOn: 2026-06-24T18:23:24.0000000Z
template: cliagent-1.0.0
language: 1033